  name: CI/CD

  on:
    push:
      branches:
        - master
 
  
  jobs:
    my_testing:
      runs-on: ubuntu-latest
  
      steps:
      - name: print hello massage in testing
        run: echo "Hello world"

      my_deploy:
        runs-on: ubuntu-latest
        needs: [my_testing]

        steps:
        - name: print hello massage
        run : echo "hello world from me"
