#-------------------------------------
# Ci і CD інтиграція в Githab Action 
#
#
#-------------------------------------
name: Ci
on: 
  push:
    branches:
       - master

jobs:
  my_testing:

  run-on: ubuntu-latest

  s
